---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [210]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [211]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [212]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [213]:
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

In [214]:
df['Gold'].describe()

count    146.000000
mean      32.938356
std       96.745184
min        0.000000
25%        0.000000
50%        3.000000
75%       23.000000
max      976.000000
Name: Gold, dtype: float64

In [215]:
df[df['Gold']==976]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [216]:
def answer_one():
    return "United States"

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [217]:
df['sg-wg']=df['Gold']-df['Gold.1']

In [218]:
df['sg-wg'].describe()

count    146.000000
mean      26.369863
std       85.756754
min      -62.000000
25%        0.000000
50%        2.000000
75%       17.750000
max      880.000000
Name: sg-wg, dtype: float64

In [219]:
df['Gold.1'].describe()

count    146.000000
mean       6.568493
std       18.975086
min        0.000000
25%        0.000000
50%        0.000000
75%        0.750000
max      118.000000
Name: Gold.1, dtype: float64

In [220]:
df[df['sg-wg']==880]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,sg-wg
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA,880

In [221]:
def answer_two():
    return "United States"

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [222]:
da=df[(df['Gold']>0) & (df['Gold.1']>0)]
da.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,sg-wg
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS,134
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT,-41
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR,6
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL,36
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL,50

In [223]:
da['rg']=da['sg-wg']/da['Gold.2']
da['rg'].describe()

count    36.000000
mean      0.550753
std       0.364491
min      -0.532468
25%       0.373434
50%       0.630208
75%       0.863445
max       0.961538
Name: rg, dtype: float64

In [224]:
da[da['rg']==da['rg'].max()]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,sg-wg,rg
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL,50,0.961538

In [225]:
def answer_three():
    return "Bulgaria"

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [226]:
df['Points']=df['Gold.2']*3+df['Silver.2']*2+df['Bronze.2']*1

In [227]:
df['Points'].describe()

count     146.000000
mean      238.684932
std       604.613148
min         1.000000
25%         4.000000
50%        23.000000
75%       170.250000
max      5684.000000
Name: Points, dtype: float64

In [228]:
def answer_four():
    return df['Points']

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [229]:
census_df = pd.read_csv('census.csv')
census_df.tail(115)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
3078,50,3,5,54,75,West Virginia,Pocahontas County,8719,8722,8712,...,14.024286,-13.343978,0.230203,2.191465,-6.019215,14.594379,-13.115876,0.460405,2.422145,-5.787707
3079,50,3,5,54,77,West Virginia,Preston County,33520,33520,33551,...,2.530967,7.287701,-5.296563,4.941121,2.063710,2.530967,7.317326,-5.266973,5.000296,2.122673
3080,50,3,5,54,79,West Virginia,Putnam County,55486,55508,55650,...,5.476902,6.213937,0.070684,2.308695,-1.899552,5.673784,6.817577,0.671503,2.978393,-1.248780
3081,50,3,5,54,81,West Virginia,Raleigh County,78859,78862,78900,...,2.821803,-2.035218,-6.013550,-5.780273,-7.811647,3.745532,-0.948083,-4.820989,-4.376675,-6.398355
3082,50,3,5,54,83,West Virginia,Randolph County,29405,29405,29369,...,3.979524,1.325381,5.324380,-6.321263,-3.868538,4.149589,1.495302,5.493946,-6.151336,-3.697364
3083,50,3,5,54,85,West Virginia,Ritchie County,10449,10449,10406,...,-4.912822,-5.041202,-11.891308,-3.485014,3.701666,-4.816492,-5.041202,-11.891308,-3.485014,3.701666
3084,50,3,5,54,87,West Virginia,Roane County,14926,14926,14876,...,-3.165836,-8.673850,-0.409263,1.847543,-9.848485,-3.165836,-8.741614,-0.477473,1.779116,-9.917355
3085,50,3,5,54,89,West Virginia,Summers County,13927,13927,13941,...,0.503543,-1.737179,-10.984183,-10.874423,2.486063,0.791282,-1.737179,-10.984183,-10.874423,2.486063
3086,50,3,5,54,91,West Virginia,Taylor County,16895,16890,16887,...,4.612792,4.774817,0.764931,4.346932,-7.713823,4.612792,4.774817,0.764931,4.346932,-7.713823
3087,50,3,5,54,93,West Virginia,Tucker County,7141,7141,7115,...,-4.094599,-9.146124,3.021800,2.589742,6.181269,-4.094599,-9.146124,3.021800,2.589742,6.181269
3088,50,3,5,54,95,West Virginia,Tyler County,9208,9211,9184,...,-0.546896,-4.081633,-3.775680,11.738649,-11.188656,-0.546896,-4.081633,-3.775680,11.738649,-11.188656
3089,50,3,5,54,97,West Virginia,Upshur County,24254,24254,24245,...,0.865962,8.329914,3.582916,1.703750,2.266151,0.824725,8.370948,3.623631,1.784881,2.347085
3090,50,3,5,54,99,West Virginia,Wayne County,42481,42484,42442,...,-11.423696,-4.806370,-1.104163,-7.552724,-4.621241,-11.162989,-4.615072,-0.912135,-7.311423,-4.378017
3091,50,3,5,54,101,West Virginia,Webster County,9154,9154,9155,...,-1.856402,-12.758469,-12.631344,-4.407278,-7.165198,-1.528802,-12.538495,-12.295998,-3.955249,-6.710264
3092,50,3,5,54,103,West Virginia,Wetzel County,16583,16580,16552,...,-7.099945,4.022918,-9.881241,-9.392007,-6.731677,-6.735846,4.144825,-9.758493,-9.267610,-6.605851
3093,50,3,5,54,105,West Virginia,Wirt County,5717,5717,5745,...,6.757342,3.444119,8.554320,-9.222099,5.120765,7.450403,3.960737,9.238666,-8.538980,5.803533
3094,50,3,5,54,107,West Virginia,Wood County,86956,86956,87016,...,-1.127428,-1.695355,-0.843584,0.323834,0.161950,-1.092915,-1.603091,-0.774249,0.439489,0.289196
3095,50,3,5,54,109,West Virginia,Wyoming County,23796,23801,23718,...,-7.122115,-6.125377,-6.063362,-12.003430,-12.351480,-7.122115,-6.125377,-6.063362,-12.003430,-12.351480
3096,40,2,3,55,0,Wisconsin,Wisconsin,5686986,5687289,5690204,...,-1.088077,-1.665772,-1.328675,-1.641820,-2.700254,-0.057895,-0.510312,-0.070444,-0.164130,-1.213969
3097,50,2,3,55,1,Wisconsin,Adams County,20875,20875,20864,...,7.469833,-13.276686,5.510985,-8.701851,2.726687,7.517717,-13.131850,5.754834,-8.357710,3.172872
3098,50,2,3,55,3,Wisconsin,Ashland County,16157,16157,16163,...,-5.210110,-12.316734,8.634714,2.427411,-12.782355,-5.086060,-12.191691,8.759855,2.551894,-12.657038
3099,50,2,3,55,5,Wisconsin,Barron County,45870,45870,45840,...,1.024523,-4.928472,-4.811057,-4.585495,-0.614939,1.504087,-3.859909,-3.630161,-3.225205,0.746711
3100,50,2,3,55,7,Wisconsin,Bayfield County,15014,15014,15011,...,7.172029,-0.927152,4.370282,-8.911352,2.805518,7.636883,-0.463576,4.833797,-8.379331,3.339902
3101,50,2,3,55,9,Wisconsin,Brown County,248007,248007,248507,...,0.965796,2.073066,-1.630833,-0.355980,-0.624871,2.372413,3.606022,-0.003939,1.607777,1.319604
3102,50,2,3,55,11,Wisconsin,Buffalo County,13587,13587,13555,...,-4.068800,-12.451536,-0.598802,-12.866333,-2.045687,-3.698909,-12.227856,-0.299401,-12.565366,-1.742622
3103,50,2,3,55,13,Wisconsin,Burnett County,15457,15457,15433,...,4.976893,-7.190749,0.456323,4.112674,-3.477804,5.235433,-6.931623,0.717080,4.439077,-3.149710
3104,50,2,3,55,15,Wisconsin,Calumet County,48971,48971,49008,...,6.564418,-6.154836,-5.471901,-6.310929,1.430500,6.969629,-5.792787,-5.089673,-5.867350,1.893901
3105,50,2,3,55,17,Wisconsin,Chippewa County,62415,62505,62616,...,1.083398,-2.620233,-0.174340,2.101604,-0.315112,1.163059,-2.509072,-0.063396,2.243818,-0.173312
3106,50,2,3,55,19,Wisconsin,Clark County,34690,34691,34682,...,-6.194359,-15.318140,-5.737883,-11.052288,-5.171562,-5.618139,-15.000217,-5.390133,-10.588150,-4.706703
3107,50,2,3,55,21,Wisconsin,Columbia County,56833,56833,56867,...,-5.125134,-5.727873,-0.230023,-1.131112,0.494202,-4.984237,-5.515730,0.000000,-0.848334,0.794253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [230]:
gp=census_df.groupby('STNAME')

In [231]:
for i in gp.groups:
    print(len(gp.groups[i]))
    if len(gp.groups[i])==255:
        print(i)

68
30
16
76
59
65
9
4
2
68
160
6
45
103
93
100
106
121
65
17
25
15
84
88
83
116
57
94
18
11
22
34
63
101
54
89
78
37
68
6
47
67
96
255
Texas
30
15
134
40
56
73
24

In [232]:
def answer_five():
    return "Texas"

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [233]:
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [234]:
gp_obj2 = census_df.groupby(['STNAME'])
import numpy as np

In [235]:
my_df=census_df[census_df['SUMLEV']==50]

In [236]:
my_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [237]:
new_df = my_df.groupby(['STNAME']).agg({"CENSUS2010POP":np.sum}).unstack()
new_df

               STNAME
CENSUS2010POP  Alabama                  4779736
               Alaska                    710231
               Arizona                  6392017
               Arkansas                 2915918
               California              37253956
               Colorado                 5029196
               Connecticut              3574097
               Delaware                  897934
               District of Columbia      601723
               Florida                 18801310
               Georgia                  9687653
               Hawaii                   1360301
               Idaho                    1567582
               Illinois                12830632
               Indiana                  6483802
               Iowa                     3046355
               Kansas                   2853118
               Kentucky                 4339367
               Louisiana                4533372
               Maine                    1328361
               Maryland                 5773552
               Massachusetts            6547629
               Michigan                 9883640
               Minnesota                5303925
               Mississippi              2967297
               Missouri                 5988927
               Montana                   989415
               Nebraska                 1826341
               Nevada                   2700551
               New Hampshire            1316470
               New Jersey               8791894
               New Mexico               2059179
               New York                19378102
               North Carolina           9535483
               North Dakota              672591
               Ohio                    11536504
               Oklahoma                 3751351
               Oregon                   3831074
               Pennsylvania            12702379
               Rhode Island             1052567
               South Carolina           4625364
               South Dakota              814180
               Tennessee                6346105
               Texas                   25145561
               Utah                     2763885
               Vermont                   625741
               Virginia                 7994802
               Washington               6724540
               West Virginia            1852994
               Wisconsin                5686986
               Wyoming                   563626
dtype: int64

In [238]:
new_df=my_df.sort_values(['STNAME', 'CENSUS2010POP'], ascending=[True, False])
new_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
37,50,3,6,1,73,Alabama,Jefferson County,658466,658350,658116,...,-4.138628,-4.492646,-1.664873,-0.970225,-3.337536,-2.985041,-3.536344,-0.647113,0.221333,-2.126089
49,50,3,6,1,97,Alabama,Mobile County,412992,413143,413332,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
45,50,3,6,1,89,Alabama,Madison County,334811,334811,336138,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881
51,50,3,6,1,101,Alabama,Montgomery County,229363,229363,229723,...,0.793549,-17.053618,-16.353778,-8.910671,-5.820167,2.441356,-15.057012,-14.486528,-6.784461,-3.598965
59,50,3,6,1,117,Alabama,Shelby County,195085,195218,196048,...,1.456731,7.783057,8.805327,5.037501,5.986812,3.065733,8.755939,9.897345,6.359052,7.307574

In [239]:
final=new_df.groupby('STNAME').head(3)

In [240]:
final_df=pd.DataFrame(final.groupby(['STNAME']).agg({"CENSUS2010POP":np.sum}).unstack())

In [241]:
type(final_df)

pandas.core.frame.DataFrame

In [242]:
final_df.columns=['0']

In [243]:
final_df.sort_values(['0'], ascending= False)

                                           0
              STNAME
CENSUS2010POP California            15924150
              Texas                  8269632
              Illinois               6815061
              New York               6321295
              Florida                5564635
              Arizona                5173150
              Michigan               3863924
              Pennsylvania           3549228
              Washington             3439809
              Ohio                   3245910
              Massachusetts          3044796
              Connecticut            2673320
              Maryland               2640226
              New Jersey             2498943
              Nevada                 2427950
              Georgia                2417795
              North Carolina         2309027
              Minnesota              2059617
              Missouri               2033597
              Tennessee              1986551
              Virginia               1921722
              Utah                   1852698
              Wisconsin              1825699
              Colorado               1794424
              Indiana                1754727
              Oregon                 1641036
              Oklahoma               1577791
              Alabama                1406269
              Hawaii                 1293120
              Kansas                 1220478
              Louisiana              1216552
              Kentucky               1196619
              South Carolina         1185938
              New Mexico             1015967
              Nebraska                961357
              Rhode Island            919804
              Delaware                897934
              New Hampshire           842389
              Arkansas                807152
              Iowa                    807090
              Idaho                   719782
              Maine                   632728
              District of Columbia    601723
              Mississippi             593642
              Alaska                  478402
              West Virginia           393551
              Montana                 348199
              South Dakota            315244
              North Dakota            297947
              Vermont                 277721
              Wyoming                 213321

In [244]:
population_list=['California','Texas','Illinois']

In [245]:
def answer_six():
    return population_list

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [246]:
da=census_df[census_df['SUMLEV']==50]
da=da[['CTYNAME','POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
da.head()

,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Autauga County,54660,55253,55175,55038,55290,55347
2,Baldwin County,183193,186659,190396,195126,199713,203709
3,Barbour County,27341,27226,27159,26973,26815,26489
4,Bibb County,22861,22733,22642,22512,22549,22583
5,Blount County,57373,57711,57776,57734,57658,57673

In [247]:
da['max']=da.max(axis=1)
da['min']=da.min(axis=1)
da.head()

,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,max,min
1,Autauga County,54660,55253,55175,55038,55290,55347,55347,54660
2,Baldwin County,183193,186659,190396,195126,199713,203709,203709,183193
3,Barbour County,27341,27226,27159,26973,26815,26489,27341,26489
4,Bibb County,22861,22733,22642,22512,22549,22583,22861,22512
5,Blount County,57373,57711,57776,57734,57658,57673,57776,57373

In [248]:
da['max-min']=da['max']-da['min']
da.head()

,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,max,min,max-min
1,Autauga County,54660,55253,55175,55038,55290,55347,55347,54660,687
2,Baldwin County,183193,186659,190396,195126,199713,203709,203709,183193,20516
3,Barbour County,27341,27226,27159,26973,26815,26489,27341,26489,852
4,Bibb County,22861,22733,22642,22512,22549,22583,22861,22512,349
5,Blount County,57373,57711,57776,57734,57658,57673,57776,57373,403

In [249]:
da[da['max-min']==da['max-min'].max()]

,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,max,min,max-min
2667,Harris County,4108187,4181238,4262504,4352462,4447577,4538028,4538028,4108187,429841

In [250]:
def answer_seven():
    return "Harris County"

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [251]:
census_da=census_df[(census_df['REGION']==1) |(census_df['REGION']==2)]
len(census_da)

1293

In [252]:
census_da=census_da[census_da['POPESTIMATE2015']-census_da['POPESTIMATE2014']>0]
len(census_da)

510

In [253]:
census_da.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
315,50,1,1,9,1,Connecticut,Fairfield County,916829,916850,919744,...,-0.228261,-3.030708,-2.070291,-6.633789,-7.385939,6.119788,2.687406,4.096896,0.441829,-0.338989
618,50,2,3,17,19,Illinois,Champaign County,201081,201081,201489,...,-7.576020,-8.039119,-6.182524,-7.995954,-8.763227,0.767004,0.467105,2.996108,2.405562,1.494169
625,50,2,3,17,33,Illinois,Crawford County,19817,19817,19811,...,-0.454603,-9.489736,-5.928803,-4.423982,3.299905,0.050511,-8.880769,-5.366589,-3.755241,3.970198
628,50,2,3,17,39,Illinois,De Witt County,16561,16561,16586,...,-1.508705,-5.384476,-6.445336,-6.189674,3.262241,-1.508705,-5.384476,-6.445336,-6.189674,3.262241
633,50,2,3,17,49,Illinois,Effingham County,34242,34242,34224,...,-1.255291,-0.844890,-3.552656,-4.370629,-0.960811,-0.934170,-0.611817,-3.319695,-4.108392,-0.698771

In [254]:
census_da=census_da[census_da['CTYNAME'].str.contains('^Washington')==True]

In [255]:
census_da=census_da[['STNAME','CTYNAME']]
census_da

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [256]:
def answer_eight():
    return census_da